# Generated by Django 2.0.5 on 2018-05-04 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='your_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='choice',
            new_name='User_type',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='username',
            new_name='Username',
        ),
    ]
