# Generated by Django 2.0.5 on 2018-05-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_auto_20180504_0416'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upload_image', models.ImageField(default='images/None/no-img.jpg', upload_to='images/')),
                ('Discription', models.TextField(max_length=500)),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
