# Generated by Django 2.0.5 on 2018-05-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetails',
            name='Product_name',
            field=models.TextField(default='absaghsgjhasjkajsjka', max_length=20),
            preserve_default=False,
        ),
    ]
