# Generated by Django 2.0.5 on 2018-05-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0004_itemdetails_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='Product_name',
            field=models.TextField(max_length=5),
        ),
    ]
