# Generated by Django 2.0.5 on 2018-05-10 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0006_auto_20180510_0626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='username',
            new_name='user',
        ),
        migrations.AddField(
            model_name='itemdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='Price',
            field=models.IntegerField(default=0),
        ),
    ]
